---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mosb6374/vuejs/vue-project
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH